# Generated by Django 3.0.8 on 2020-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='id',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
