# Generated by Django 3.0.8 on 2020-07-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200730_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mess_id',
            new_name='mess_no',
        ),
    ]
