# Generated by Django 3.0.8 on 2020-07-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200730_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
