# Generated by Django 3.0.8 on 2020-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('mess_no', models.AutoField(db_column='bid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=350)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
