# Generated by Django 3.0.8 on 2020-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200730_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mess_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
