# Generated by Django 3.0.8 on 2020-07-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200730_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
