# Generated by Django 3.0.8 on 2020-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200730_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_no',
        ),
        migrations.AddField(
            model_name='videos',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
