# Generated by Django 3.0.8 on 2020-07-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200730_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
