# Generated by Django 3.0.7 on 2020-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200730_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mess_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('desc', models.CharField(default='', max_length=1500)),
            ],
        ),
    ]
